name: Dependabot auto-merge
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: '1609696'
          private-key: ${{ secrets.APP_KEY }}
          
      - name: Auto-approve PRs
        uses: hmarr/auto-approve-action@v4
        if: ${{ steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        with:
          github-token: ${{ steps.app-token.outputs.token }}
      
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
